name: Terraform Check

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: [day1, day2, day3, day4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ matrix.dir }}

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{ matrix.dir }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.dir }}

      - name: Terraform Plan
        run: |
          if [ -f "dev.tfvars" ]; then
            terraform plan -var-file="dev.tfvars"
          else
            terraform plan
          fi
        working-directory: ${{ matrix.dir }}